spring:
  application:
    name: file-service
server:
  port: 8087
eureka:
  instance:
    prefer-ip-address: true #注册服务使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 47.100.121.59:22122